### ISSUE TITLE
Local git config doesn't have your account details

### ISSUE THREAD

**Issue by nikclayton** [buliasz/open-sudoku-2#1]
FYI @buliasz , looking at the commit history https://github.com/buliasz/open-sudoku-2/commits/main/ I'm guessing your local git configuraiton is not set up to correctly record commits with your account information, so almost every commit is associated with "Your name". You probably want to fix that.

**Comment by buliasz** [comment]
Thanks Nick, fixed it. After merge with Open Sudoku (1) it should be valid.
