### ISSUE TITLE
Hosting the privacy policy

### ISSUE THREAD

**Issue by nikclayton** [buliasz/open-sudoku-2#2]
FYI, it's been my experience that Google reviewers will object to privacy policies that are hosted solely on GitHub.

I think they consider a GitHub URL to be "editable", and this falls foul of the "Be non-editable." requirement.

There's a few more details about this in https://pachli.app/pachli/2023/10/05/1.2-release.htm.

Probably the easiest fix, if this happens, is to create a GitHub Pages site and host it there. They had no objections to that.

**Comment by buliasz** [comment]
Thank you. As you probably know already, I've just announced that we'll be moving back to Open Sudoku repository so the original one will be used. It's a huge change so will take some time though.
